import type { Dataset, License, TrainingJob, AccessLog, GovernanceProposal } from "./types"

export const mockDatasets: Dataset[] = [
  {
    id: "dataset-001",
    title: "Clinical Imaging Collection",
    description: "Anonymized medical imaging data including X-rays, MRIs, and CT scans with professional annotations.",
    organization: "Anonymous Hospital Network Alpha",
    organizationType: "healthcare",
    price: 2500,
    tags: ["healthcare", "imaging", "diagnosis", "radiology"],
    size: "2.3 GB",
    createdAt: "2023-10-15",
    image: "/medical-imaging-data.png",
    dataType: "image",
    domain: "healthcare",
    accessType: "restricted",
    accessCount: 1245,
    sampleAvailable: true,
    privacyTechnique: "anonymization",
    qualityScore: 92,
    updateFrequency: "Quarterly",
  },
  {
    id: "dataset-002",
    title: "Financial Market Indicators",
    description:
      "Historical financial indicators and market trends with minute-level resolution, anonymized by institution.",
    organization: "Financial Research Consortium Beta",
    organizationType: "research",
    price: 1800,
    tags: ["finance", "time series", "market analysis"],
    size: "1.8 GB",
    createdAt: "2023-11-02",
    image: "/placeholder.svg?key=djkn3",
    dataType: "timeseries",
    domain: "finance",
    accessType: "commercial",
    accessCount: 876,
    sampleAvailable: true,
    privacyTechnique: "differential-privacy",
    qualityScore: 88,
    updateFrequency: "Daily",
  },
  {
    id: "dataset-003",
    title: "Genomic Research Database",
    description: "De-identified genomic sequences for research in bioinformatics and genetic analysis.",
    organization: "Research Institute Gamma",
    organizationType: "research",
    price: 3200,
    tags: ["genomics", "biology", "research", "sequences"],
    size: "5.7 GB",
    createdAt: "2023-09-28",
    image: "/genomic-data-visualization.png",
    dataType: "tabular",
    domain: "biology",
    accessType: "restricted",
    accessCount: 432,
    sampleAvailable: false,
    privacyTechnique: "anonymization",
    qualityScore: 95,
    updateFrequency: "Annually",
  },
  {
    id: "dataset-004",
    title: "Multilingual Conversation Corpus",
    description:
      "A large corpus of anonymized conversational text in multiple languages for natural language processing.",
    organization: "Language Research Collective Delta",
    organizationType: "education",
    price: 1200,
    tags: ["nlp", "text", "language", "multilingual"],
    size: "1.2 GB",
    createdAt: "2023-12-05",
    image: "/language-processing-data.png",
    dataType: "text",
    domain: "linguistics",
    accessType: "open",
    accessCount: 2156,
    sampleAvailable: true,
    privacyTechnique: "differential-privacy",
    qualityScore: 87,
    updateFrequency: "Monthly",
  },
  {
    id: "dataset-005",
    title: "Urban Traffic Patterns",
    description:
      "Anonymized traffic flow data from urban centers, including vehicle counts, speeds, and congestion metrics.",
    organization: "Smart City Initiative Epsilon",
    organizationType: "government",
    price: 1500,
    tags: ["urban", "traffic", "transportation", "smart city"],
    size: "8.9 GB",
    createdAt: "2023-08-17",
    image: "/traffic-data-visualization.png",
    dataType: "timeseries",
    domain: "urban planning",
    accessType: "commercial",
    accessCount: 345,
    sampleAvailable: true,
    privacyTechnique: "anonymization",
    qualityScore: 83,
    updateFrequency: "Weekly",
  },
  {
    id: "dataset-006",
    title: "Consumer Behavior Analytics",
    description: "Anonymized consumer behavior data with purchasing patterns and preferences, fully de-identified.",
    organization: "Market Research Group Zeta",
    organizationType: "commercial",
    price: 2800,
    tags: ["consumer", "behavior", "marketing", "analytics"],
    size: "3.4 GB",
    createdAt: "2023-10-30",
    image: "/consumer-behavior-analytics.png",
    dataType: "tabular",
    domain: "marketing",
    accessType: "commercial",
    accessCount: 567,
    sampleAvailable: true,
    privacyTechnique: "differential-privacy",
    qualityScore: 90,
    updateFrequency: "Monthly",
  },
  {
    id: "dataset-007",
    title: "Environmental Sensor Readings",
    description: "Time-series data from environmental sensors measuring air quality, temperature, and other metrics.",
    organization: "Environmental Monitoring Network Eta",
    organizationType: "nonprofit",
    price: 800,
    tags: ["environment", "climate", "sensors", "monitoring"],
    size: "4.2 GB",
    createdAt: "2023-07-12",
    image: "/environmental-sensor-data.png",
    dataType: "timeseries",
    domain: "environmental science",
    accessType: "open",
    accessCount: 1892,
    sampleAvailable: true,
    privacyTechnique: "none",
    qualityScore: 94,
    updateFrequency: "Real-time",
  },
  {
    id: "dataset-008",
    title: "Educational Performance Metrics",
    description: "Anonymized student performance data across various educational institutions and programs.",
    organization: "Education Research Consortium Theta",
    organizationType: "education",
    price: 1100,
    tags: ["education", "performance", "analytics", "learning"],
    size: "1.5 GB",
    createdAt: "2023-11-20",
    image: "/education-data-visualization.png",
    dataType: "tabular",
    domain: "education",
    accessType: "restricted",
    accessCount: 423,
    sampleAvailable: false,
    privacyTechnique: "anonymization",
    qualityScore: 86,
    updateFrequency: "Semester-based",
  },
]

export const mockLicenses: License[] = [
  {
    id: "license-001",
    datasetId: "dataset-001",
    licensee: "Research Organization XYZ",
    purchasedAt: "2023-11-15",
    expiresAt: "2024-11-15",
    accessCount: 12,
    maxAccessCount: 100,
    termsAccepted: true,
    usageRestrictions: ["no-redistribution", "research-only", "no-commercial-use"],
  },
  {
    id: "license-002",
    datasetId: "dataset-003",
    licensee: "Healthcare Provider ABC",
    purchasedAt: "2023-12-02",
    expiresAt: "2024-12-02",
    accessCount: 5,
    maxAccessCount: 50,
    termsAccepted: true,
    usageRestrictions: ["no-redistribution", "internal-use-only"],
  },
]

export const mockTrainingJobs: TrainingJob[] = [
  {
    id: "job-001",
    datasetId: "dataset-001",
    status: "completed",
    progress: 100,
    startedAt: "2023-12-10T14:30:00Z",
    completedAt: "2023-12-10T16:45:00Z",
    modelType: "ResNet50",
    modelSize: "98 MB",
    outputUrl: "https://example.com/models/resnet50-trained.h5",
  },
  {
    id: "job-002",
    datasetId: "dataset-004",
    status: "running",
    progress: 68,
    startedAt: "2023-12-15T09:15:00Z",
    modelType: "BERT-Base",
    modelSize: "440 MB",
  },
  {
    id: "job-003",
    datasetId: "dataset-003",
    status: "pending",
    progress: 0,
    startedAt: "2023-12-16T11:00:00Z",
    modelType: "UNet",
    modelSize: "120 MB",
  },
]

export const mockAccessLogs: AccessLog[] = [
  {
    id: "log-001",
    datasetId: "dataset-001",
    user: "Research Organization XYZ",
    timestamp: "2023-12-10T14:25:00Z",
    action: "download",
    success: true,
  },
  {
    id: "log-002",
    datasetId: "dataset-001",
    user: "Research Organization XYZ",
    timestamp: "2023-12-10T14:30:00Z",
    action: "train",
    success: true,
  },
  {
    id: "log-003",
    datasetId: "dataset-003",
    user: "Healthcare Provider ABC",
    timestamp: "2023-12-12T10:15:00Z",
    action: "view",
    success: true,
  },
  {
    id: "log-004",
    datasetId: "dataset-004",
    user: "Education Institution DEF",
    timestamp: "2023-12-14T16:40:00Z",
    action: "download",
    success: false,
  },
]

export const mockGovernanceProposals: GovernanceProposal[] = [
  {
    id: "prop-001",
    title: "Reduce License Fees for Academic Use",
    description: "Proposal to reduce license fees by 50% for verified academic institutions.",
    proposer: "Education Research Consortium Theta",
    status: "active",
    votes: {
      yes: 1250000,
      no: 750000,
    },
    createdAt: "2023-12-01",
    endsAt: "2023-12-15",
  },
  {
    id: "prop-002",
    title: "Implement Differential Privacy Standards",
    description: "Proposal to require all datasets to implement differential privacy with epsilon <= 3.",
    proposer: "Research Institute Gamma",
    status: "passed",
    votes: {
      yes: 2100000,
      no: 450000,
    },
    createdAt: "2023-11-15",
    endsAt: "2023-11-30",
  },
  {
    id: "prop-003",
    title: "Increase Protocol Fee for Commercial Licenses",
    description: "Proposal to increase protocol fee from 2% to 3% for commercial license transactions.",
    proposer: "Market Research Group Zeta",
    status: "rejected",
    votes: {
      yes: 800000,
      no: 1900000,
    },
    createdAt: "2023-11-01",
    endsAt: "2023-11-15",
  },
]
